### ISSUE TITLE
1.0 Todo

### ISSUE THREAD

**Issue by traverseda** [traverseda/iiab-searchServices#2]
- [ ] Ability to remove data from the search index
 - [ ] Use session based URL dedupe instead of timestamps
 - [ ] Ability to tune indexer for different memory scenarios
   - [ ] Singleton huey tasks, route all search index calls to a single process
